apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp1
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp3
        image: wil42/playground:v1
        ports:
        - containerPort: 8080

